apiVersion: v1
kind: Pod
metadata:
  name: example-container
spec:
#  activeDeadlineSeconds: 1800  # Pod terminates after 30 min
  securityContext:
    runAsUser: 233998 # run id command in terminal to get your UID
    runAsGroup: 104023
  containers:
    - name: example-container
      image: ghcr.io/yisi-alisa-yang/feb_25_template_alisa:main  # image name
      resources:
        requests: # minimum resources
          memory: "16Gi"
          cpu: "8"
        limits: # maximum resources
          memory: "24Gi"
          cpu: "16"
      volumeMounts:
      - name: home
        mountPath: "/app"
      command: ["/bin/sh"]
      stdin: true
      tty: true
  volumes:
  - name: home
    nfs:
      server: 128.239.56.166
      path: /sciclone/home/yyang30/Feb_25_Template_Alisa